server:
  port: 3000

db:
 type: 'mysql'
 port: 3306
 database: 'hrmini'
 host: localhost
 username: root
 password: ''
#  database: hrmini
#  host: db4free.net
#  username: kareemayodeji
#  password: Kareem'shrmini

jwt:
  expiresIn: '1h'
 